#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M4F{1,0,5.2,6
#
Projection_Clock.xem4f: package/cfg/Projection_Clock.xem4f.mak

clean::
	-$(RM) package/cfg/Projection_Clock.xem4f.mak
